"""Remine diversified hard frames from known low-det + high-det recordings."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from aigp.core.params import ParamSet  # noqa: E402
from analysis.eval_detector_scale import (  # noqa: E402
    HsvGateDetector,
    eval_recording,
    save_hard_frames,
)


def main() -> int:
    params = ParamSet.load(ROOT / "config" / "params_default.json")
    detector = HsvGateDetector(params)
    targets = [
        Path(r"C:\Users\tsion\Projects\eni_dcim_phase1\logs\20260714T045635-b9a568ab\vision.aigprec"),
        Path(r"C:\Users\tsion\Projects\eni_dcim_phase1\logs\20260714T072732-8ff375f3\vision.aigprec"),
        Path(r"C:\Users\tsion\Projects\eni_dcim_phase1\logs\20260714T081945-bb5494d6\vision.aigprec"),
        Path(r"C:\Users\tsion\Projects\eni_dcim_phase1\logs\20260713T202513-ea4b5f0c\vision.aigprec"),
        Path(r"C:\Users\tsion\Projects\eni_dcim_phase1\logs\20260714T041536-88e6e576\vision.aigprec"),
    ]
    hard_pool: list = []
    for path in targets:
        print(f"Remining {path.parent.name}/{path.name} ...", flush=True)
        st = eval_recording(path, detector, hard_pool, hard_keep=80, stride=1)
        print(
            f"  frames={st.frames} det={st.detection_rate:.1f}% pool={len(hard_pool)}",
            flush=True,
        )

    hard_meta = save_hard_frames(
        hard_pool, ROOT / "analysis" / "hard_frames", n=40, per_recording_cap=8
    )
    metrics_path = ROOT / "analysis" / "detector_eval_metrics.json"
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    metrics["hard_frames"] = hard_meta
    metrics["hard_frame_policy"] = "parent_keyed_diversity_cap8"
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")

    # Rewrite markdown cleanly from metrics
    lines = [
        "# Detector evaluation at scale",
        "",
        "Generated by `analysis/eval_detector_scale.py` "
        "(hard frames diversified by parent recording folder).",
        "",
        "## Per-recording summary",
        "",
        "| recording | MB | frames | det% | PnP/det% | PnP/frm% | dist mean±std (m) | center jump p95 (px) | span (s) |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    total_f = total_d = total_p = 0
    for r in metrics["recordings"]:
        st = r.get("stability") or {}
        dist = ""
        if "distance_mean_m" in st:
            dist = f"{st['distance_mean_m']:.2f}±{st['distance_std_m']:.2f}"
        cjump = f"{st['center_jump_p95_px']:.1f}" if "center_jump_p95_px" in st else ""
        span = f"{st['span_s']:.1f}" if "span_s" in st else ""
        name = Path(r["path"]).name
        parent = Path(r["path"]).parent.name
        lines.append(
            f"| `{parent}/{name}` | {r['size_mb']} | {r['frames']} | "
            f"{r['detection_rate_pct']:.1f} | {r['pnp_rate_of_detections_pct']:.1f} | "
            f"{r['pnp_rate_of_frames_pct']:.1f} | {dist} | {cjump} | {span} |"
        )
        total_f += r["frames"]
        total_d += r["detections"]
        total_p += r["pnp_ok"]

    lines += [
        "",
        "## Aggregate",
        "",
        f"- Recordings evaluated: **{len(metrics['recordings'])}**",
        f"- Frames: **{total_f}**",
        f"- Detection rate: **{(100.0 * total_d / total_f) if total_f else 0:.2f}%** "
        f"({total_d}/{total_f})",
        f"- PnP solve rate (of detections): "
        f"**{(100.0 * total_p / total_d) if total_d else 0:.2f}%** ({total_p}/{total_d})",
        f"- PnP solve rate (of frames): "
        f"**{(100.0 * total_p / total_f) if total_f else 0:.2f}%**",
        "",
        "## Cross-checks / anomalies",
        "",
    ]
    for r in metrics["recordings"]:
        st = r.get("stability") or {}
        notes = []
        if r.get("decode_failures"):
            notes.append(f"{r['decode_failures']} JPEG decode failures")
        if st.get("large_gaps_gt_50ms"):
            notes.append(
                f"{st['large_gaps_gt_50ms']} frame gaps >50ms "
                f"(max {st.get('frame_gap_max_ms', 0):.1f} ms)"
            )
        if st.get("distance_step_p95_abs_m", 0) > 2.0:
            notes.append(
                f"unstable distance steps "
                f"(p95 abs Δd={st['distance_step_p95_abs_m']:.2f} m)"
            )
        if r["frames"] and r["detection_rate_pct"] < 95.0:
            notes.append(f"detection rate below 95% ({r['detection_rate_pct']:.1f}%)")
        if not notes:
            notes.append("no major anomalies flagged")
        label = f"{Path(r['path']).parent.name}/{Path(r['path']).name}"
        lines.append(f"- `{label}`: " + "; ".join(notes))

    lines += [
        "",
        "## Hardest frames",
        "",
        f"Top {len(hard_meta)} saved under `analysis/hard_frames/`.",
        "",
        "| # | score | reason | frame | recording | file |",
        "|---:|---:|---|---:|---|---|",
    ]
    for i, h in enumerate(hard_meta):
        rec = f"{Path(h['recording']).parent.name}/{Path(h['recording']).name}"
        lines.append(
            f"| {i} | {h['score']:.0f} | `{h['reason']}` | {h['frame_id']} | "
            f"`{rec}` | `{h['file']}` |"
        )
    lines += [
        "",
        "## Notes for cloud agent",
        "",
        "- Detector `GateDetection.confidence` is hard-coded to `1.0`; "
        "hardness uses miss / PnP-fail / jump heuristics.",
        "- **Phase-2 flights show a sharp detection collapse** (5.9–17.8%) vs "
        "Phase-1 race recordings (95–97%). Likely motion blur / extreme attitude "
        "during tumbling — not a PnP failure (PnP stays ~95–100% when corners exist).",
        "- Large `.aigprec` binaries were read from the operator checkout; "
        "not copied into git.",
        "",
    ]
    (ROOT / "analysis" / "20260714-detector-eval-at-scale.md").write_text(
        "\n".join(lines), encoding="utf-8"
    )
    print(f"Saved {len(hard_meta)} hard frames + report", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
